### PR TITLE
fix bug to update firmware ref #97

### LINKED ISSUE #97: Update firmware it's not working
**Describe the bug**
Unable to update firmware through the bootloader, calling `firmwareUpdate` using go tool it's not working, the device get freezed almost finishing (look at picture). An interesting/strange behavior is thet if you unplug the device, plug it again and send a firmware(by calling `firmwareUpdate` again) the process start without a button confirmation request and the process finish properly.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64
- Firmware Version: develop

**Steps to Reproduce**
Just plug the device and try to update the firmware through the bootloader:
`go run cmd/cli/cli.go firmwareUpdate -f path/to/binary/image`

**Actual behavior**
The firmware get freezed.

**Expected behavior**
Just update the firmware.

**Additional context**
IMG_20190408_155738

**Possible implementation**
After spending some time looking for the bug in bootloader code, I recommend as a good starting point looking at https://github.com/skycoin/hardware-wallet-go/blob/master/src/device-wallet/device-wallet.go#L291

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #97

Changes:
- response for `MessageFirmwareUpload` msg is a confirmation button request

Does this change need to mentioned in CHANGELOG.md?
no

Requires changes in protobuff specs?
no

Requires testing
no

### CODE REVIEW

**Comment by olemis** [comment]
@therealssj iirc I've seen this before ... it seems to be working fine for me. What d'u think ?

File: src/device-wallet/device-wallet.go [hunk 1]
```diff
@@ -338,8 +338,14 @@ func (d *Device) FirmwareUpload(payload []byte, hash [32]byte) error {
...
-	case uint16(messages.MessageType_MessageType_Success):
-		log.Printf("Success %d! FirmwareUpload %s\n", uploadmsg.Kind, uploadmsg.Data)
+	case uint16(messages.MessageType_MessageType_ButtonRequest):
+		log.Println("Please confirm in the device if fingerprints match")
+		// Send ButtonAck
+		chunks, err = MessageButtonAck()
+		if err != nil {
+			return err
+		}
+		return d.Driver.SendToDeviceNoAnswer(d.dev, chunks)
```
Comment (therealssj) [inline src/device-wallet/device-wallet.go]: use `d.Driver.SendToDevice` and handle the response, should either be a `Success` or `Failure`
